[theme]
base = "dark"
primaryColor = "#2dd4bf"
backgroundColor = "#042f2e"
secondaryBackgroundColor = "#134e4a"
textColor = "#f0fdfa"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
